### ISSUE TITLE
Document project settings application

### ISSUE THREAD

**Issue by ClementHector** [quadproduction/ayon-documentation#16]

**Comment by SherineKB** [comment]
PR : https://github.com/ynput/ayon-documentation/pull/63

**Comment by ClementHector** [comment]
Can you resolve the conflict and fix the PR like the blender PR https://github.com/ynput/ayon-documentation/pull/60

**Comment by BenSouchet** [comment]
Will be merged into our codebase in the next release 3.15.12-quad.3.14
