### ISSUE TITLE
Document project settings substance painter

### ISSUE THREAD

**Issue by ClementHector** [quadproduction/ayon-documentation#6]

**Comment by SherineKB** [comment]
This ticket is blocked because on this day, the Color Management (OCIO managed) isn't working yet, and I don't know what to say about the Shelves.


![Image](https://github.com/quadproduction/ayon-documentation/assets/130908605/2a75cf70-bd79-4251-8336-4033159dd4ea)

**Comment by BenSouchet** [comment]
Removing the ticket from the main GitHub board since we won't do this task in the near future.
